dist: trusty
sudo: required
language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    - 0.6
env:
  global:
    - PYCALL_DEBUG_BUILD="yes"
  matrix:
    - PYTHON=python  # python 2.7
    - PYTHON=python3 # python 3.5
matrix:
  exclude:
    - os: osx
      env: PYTHON=python3 # not sure how to install Python 3 on Travis OSX
before_install:
    - test "x$TRAVIS_OS_NAME" = xosx -o "x$PYTHON" = xConda-python || (sudo apt-get -qq update && sudo apt-get install -y $PYTHON)
    - test "x$TRAVIS_OS_NAME" = xosx -o "x$PYTHON" = xConda-python || (sudo apt-get install $PYTHON$"-pip")

install:
    - sudo $PYTHON -m pip install git+https://github.com/weecology/retriever.git
after_success:
    - julia -e 'cd(Pkg.dir("Retriever")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
notifications:
    email: false
